stages:
  - install
  - sonar

variables:
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
  NODE_ENV: "development"

cache:
  paths:
    - node_modules/

# 1. Bağımlılıkları yükle
install_dependencies:
  image: node:18
  stage: install
  script:
    - npm ci
  only:
    - develop

# 2. SonarQube analizi
sonar_scan:
  image: sonarsource/sonar-scanner-cli:latest
  stage: sonar
  script:
    - sonar-scanner \
      -Dsonar.projectKey=angular_project_key \
      -Dsonar.sources=src \
      -Dsonar.exclusions=**/*.spec.ts \
      -Dsonar.host.url=$SONAR_HOST_URL \
      -Dsonar.login=$SONAR_TOKEN
  only:
    - develop
  dependencies:
    - install_dependencies
