export interface ILoadSheetModalsResponse {
  id?: number;
  status?: string;
  flightInfo?: {
    id?: number;
    lastUpdater?: string;
    flightISN?: number;
    airlineCode?: string;
    flightStatus?: string;
    flightNo?: string;
    flightType?: string;
    flightSuffix?: string | null;
    departurePort?: string;
    arrivalPort?: string;
    domInt?: string;
    flightDate?: string;
    flightHour?: string;
    flightDateHour?: string;
    plane?: string;
    isPreLoadSheetCreated?: null;
    isLoadSheetCreated?: null;
    cargo?: null;
    previousLeg?: null;
    nextLeg?: null;
    atd?: null;
    loadAndTrimSheets?: null;
  };
  lmc?: {
    totalPaxWeight?: number;
    totalPaxPassenger?: string;
    lmcJson?: Array<{
      spcType: string;
      spcSubType: string | null;
      spcAmount: number;
      clCpt: string;
      weight: number;
      destination: string;
      enteredBy: string | null;
      enteredDate: string;
    }>;
  };
  lastUpdater?: string;
  version?: number;
  dow?: number;
  doi?: number;
  maltow?: number;
  mallw?: number;
  taxiFuel?: number;
  si?: string;
  passengerCabinBag?: number;
  totalTrafficLoad?: number;
  zeroFuelWeightActual?: number;
  takeOffWeightActual?: number;
  landingWeightActual?: number;
  lizfw?: number;
  litow?: number;
  lilaw?: number;
  maczfw?: number;
  mactow?: number;
  maclaw?: number;
  underloadBeforeLMC?: number;
  checkedBy?: string | null;
  approvedBy?: string;
  maxZeroFuelWeight?: number;
  aircraftVersion?: string;
  aircraftType?: string;
  crewConfigurationName?: string;
  ldmMessage?: string;
  weightUnitType?: string;
  paxWeightUsed?: string;
  passengerDistribution?: string;
  totalPassenger?: string;
  holdDistribution?: string;
  totalHoldWeight?: number;
  cabinDistribution?: string;
}
